# Generated by Django 2.2.7 on 2019-12-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20191203_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
