# Generated by Django 2.2.7 on 2019-12-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_auto_20191203_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='user_id',
            new_name='player_id',
        ),
    ]
