# Generated by Django 2.2.7 on 2019-12-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20191203_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='type',
            field=models.CharField(choices=[('1', 'victory'), ('2', 'draw'), ('3', 'defeat'), ('4', 'both'), ('5', 'not_both')], max_length=8),
        ),
    ]
