# Generated by Django 2.2.7 on 2019-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0006_auto_20191204_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='cf',
        ),
        migrations.AlterField(
            model_name='bet',
            name='sum',
            field=models.PositiveIntegerField(),
        ),
    ]
