# Generated by Django 2.2.7 on 2019-12-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20191205_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.Player'),
        ),
    ]
