# Generated by Django 2.2.7 on 2019-12-05 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_auto_20191205_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=models.NullBooleanField(default=None),
        ),
    ]
