# Generated by Django 2.2.7 on 2019-12-05 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20191205_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='creation_date',
            field=models.DateField(default=datetime.date(2019, 12, 5)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='sum',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
