# Generated by Django 2.2.7 on 2019-12-12 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_auto_20191205_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='creation_date',
            field=models.DateField(default=datetime.date(2019, 12, 13)),
        ),
    ]
