# Generated by Django 2.2.7 on 2019-12-12 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0013_auto_20191213_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 23, 2, 18, 817366, tzinfo=utc)),
        ),
    ]
