# Generated by Django 2.2.7 on 2019-12-13 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0015_auto_20191213_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='cf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bet',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 18, 57, 57, 816330, tzinfo=utc)),
        ),
    ]
