# Generated by Django 2.2.7 on 2019-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('home_club', models.CharField(max_length=20)),
                ('guest_club', models.CharField(max_length=20)),
                ('home_score', models.SmallIntegerField()),
                ('guest_score', models.SmallIntegerField()),
            ],
        ),
    ]
