# Generated by Django 2.2.7 on 2019-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191203_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='both_cf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='defeat_cf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='draw_cf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='not_both',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='victory_cf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
