# Generated by Django 2.2.7 on 2019-12-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20191204_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='guest_score',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_score',
            field=models.CharField(max_length=3),
        ),
    ]
